require 'tty-prompt'

module QuizHelper
  PROMPT = TTY::Prompt.new
  PICUKI = "https://www.picuki.com/profile/goodweekendquiz".freeze
  PATH_TO_IMAGES = ["./questions.jpg", "./answers.jpg"]
  path = File.dirname(__FILE__).split("/")
  QUIZ_DATABASE = "#{path.join("/")}/../public/quizzes.json".freeze
  FACTS = ["The heads on Easter Island have bodies.", "The moon has moonquakes.", "Goosebumps are meant to ward off predators.", "There's no such thing as 'pear cider' (Cider needs apples)", "Pineapple works as a natural meat tenderizer.", "Humans are the only animals that blush.", "The feeling of getting lost inside a mall is known as the Gruen transfer.", "The wood frog can hold its pee for up to eight months.", "The hottest spot on the planet is in Libya.", "You lose up to 30 percent of your taste buds during flight.", "Your nostrils work one at a time.", "Only two mammals like spicy food: humans and the tree shrew.", "A chef's toque contains 100 folds.", "Rabbits can't puke.", "The 'M\'s' in M&Ms stand for 'Mars' and 'Murrie.'", "The human body literally glows.", "Copper door knobs are self-disinfecting.", "Fairy floss was invented by a dentist.", "Marie Curie is the only person to earn a Nobel prize in two different sciences.", "Fingernails don't grow after you die.", "The English word with the most definitions is 'set'.", "Creedence Clearwater Revival has the most No. 2 Billboard hits—without ever hitting No. 1.", "Pigeons can tell the difference between a painting by Monet and Picasso.", "The dot over the lower case 'i' or 'j' is known as a 'tittle.'", "Chewing gum boosts concentration.", "Superman didn't always fly.", "The first computer was invented in the 1940s.", "Space smells like seared steak.", "The longest wedding veil was the same length as 63.5 football fields.", "The unicorn is the national animal of Scotland.", "Bees sometimes sting other bees.", "Kids ask 300 questions a day on average.", "The total weight of ants on earth once equaled the total weight of people.", "'E' is the most common letter and appears in 11 percent of all english words.", "A dozen bodies were once found in Benjamin Franklin's basement.", "The healthiest place in the world is in Panama.", "A pharaoh once lathered his slaves in honey to keep bugs away from him.", "Some people have an extra bone in their knee (and it's getting more common).", "Pringles aren't actually potato chips.", "There's a giant fish with a transparent head.", "There's a decorated war hero dog.", "Showers really do spark creativity.", "Abraham Lincoln's bodyguard left his post at Ford's Theatre to go for a drink.", "Dolphins have been trained to be used in wars.", "Playing the accordion was once required for teachers in North Korea.", "Children's medicine once contained morphine.", "Plastic Easter eggs and plastic Easter grass were invented by a man who holds more patents than Thomas Edison.", "Water makes different pouring sounds depending on its temperature.", "Most laughter isn't because things are funny.", "One man has saved more than 200 people from suicide."]
end
